--------------------------------------------------------
-- PROYECTO: SISTEMA DE BIBLIOTECA - ENTREGA FINAL
-- EJECUTAR COMO: SYS o SYSTEM
-- Nota: Ejecutar por bloques para evitar errores de creacion
--------------------------------------------------------

-- 0. CONFIGURACIÓN CRÍTICA
ALTER SESSION SET "_oracle_script" = TRUE;

-- 1. INFRAESTRUCTURA 
--------------------------------------------------------

CREATE TABLESPACE TS_BIBLIOTECA 
DATAFILE 'ts_biblioteca.dbf' SIZE 50M AUTOEXTEND ON;

-- 2. USUARIOS
--------------------------------------------------------
CREATE USER ADMIN_BIB IDENTIFIED BY Admin12345 DEFAULT TABLESPACE TS_BIBLIOTECA;
GRANT ALL PRIVILEGES TO ADMIN_BIB;

CREATE USER BIBLIOTECARIO_PRACTICO IDENTIFIED BY Biblio12345;
GRANT CREATE SESSION TO BIBLIOTECARIO_PRACTICO;

COMMIT;

-- 3. CAMBIO DE CONTEXTO
--------------------------------------------------------
ALTER SESSION SET CURRENT_SCHEMA = ADMIN_BIB;

-- 4. OBJETOS (Tablas y Secuencias)
--------------------------------------------------------
CREATE SEQUENCE SEQ_ID_PRESTAMO MINVALUE 1 START WITH 21 INCREMENT BY 1;

CREATE TABLE LIBROS (
    ID_LIBRO NUMBER PRIMARY KEY, 
    TITULO VARCHAR2(100) NOT NULL, 
    AUTOR VARCHAR2(100), 
    STOCK NUMBER DEFAULT 10
);

CREATE TABLE USUARIOS (
    ID_USUARIO NUMBER PRIMARY KEY, 
    NOMBRE VARCHAR2(100) NOT NULL, 
    CORREO VARCHAR2(100) UNIQUE
);

CREATE TABLE PRESTAMOS (
    ID_PRESTAMO NUMBER PRIMARY KEY, 
    ID_LIBRO NUMBER, 
    ID_USUARIO NUMBER, 
    FECHA DATE,
    CONSTRAINT FK_LIB FOREIGN KEY (ID_LIBRO) REFERENCES LIBROS(ID_LIBRO),
    CONSTRAINT FK_USU FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)
);

CREATE TABLE AUDITORIA_LIBROS (
    ID_LOG NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY, 
    ID_LIBRO NUMBER, 
    TITULO_ELIMINADO VARCHAR2(100), 
    USUARIO_QUE_BORRO VARCHAR2(50), 
    FECHA_HORA TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 5. VISTA 
--------------------------------------------------------
CREATE OR REPLACE VIEW VISTA_RESUMEN_PRESTAMOS AS 
SELECT p.ID_PRESTAMO, u.NOMBRE AS LECTOR, l.TITULO AS LIBRO_PRESTADO, p.FECHA
FROM PRESTAMOS p
JOIN USUARIOS u ON p.ID_USUARIO = u.ID_USUARIO
JOIN LIBROS l ON p.ID_LIBRO = l.ID_LIBRO;

-- 6. LÓGICA (TRIGGERS)
--------------------------------------------------------
CREATE OR REPLACE TRIGGER TRG_ACTUALIZAR_STOCK_PRESTAMO
AFTER INSERT ON PRESTAMOS FOR EACH ROW
BEGIN
    UPDATE LIBROS SET STOCK = STOCK - 1 WHERE ID_LIBRO = :NEW.ID_LIBRO;
END;
/

CREATE OR REPLACE TRIGGER TRG_AUDITORIA_BORRADO
AFTER DELETE ON LIBROS FOR EACH ROW
BEGIN
    INSERT INTO AUDITORIA_LIBROS (ID_LIBRO, TITULO_ELIMINADO, USUARIO_QUE_BORRO)
    VALUES (:OLD.ID_LIBRO, :OLD.TITULO, USER);
END;
/

-- 7. DATOS Y PERMISOS FINALES
--------------------------------------------------------
-- 7.1 Insertar Libros (Variedad de autores y stock)
INSERT INTO LIBROS (ID_LIBRO, TITULO, AUTOR, STOCK) VALUES (1, 'Cien Años de Soledad', 'Gabriel García Márquez', 5);
INSERT INTO LIBROS (ID_LIBRO, TITULO, AUTOR, STOCK) VALUES (2, 'El Principito', 'Antoine de Saint-Exupéry', 10);
INSERT INTO LIBROS (ID_LIBRO, TITULO, AUTOR, STOCK) VALUES (3, 'Rayuela', 'Julio Cortázar', 3);
INSERT INTO LIBROS (ID_LIBRO, TITULO, AUTOR, STOCK) VALUES (4, '1984', 'George Orwell', 7);
INSERT INTO LIBROS (ID_LIBRO, TITULO, AUTOR, STOCK) VALUES (5, 'El Aleph', 'Jorge Luis Borges', 4);
INSERT INTO LIBROS (ID_LIBRO, TITULO, AUTOR, STOCK) VALUES (6, 'Don Quijote de la Mancha', 'Miguel de Cervantes', 2);
INSERT INTO LIBROS (ID_LIBRO, TITULO, AUTOR, STOCK) VALUES (7, 'La Tregua', 'Mario Benedetti', 6);
INSERT INTO LIBROS (ID_LIBRO, TITULO, AUTOR, STOCK) VALUES (8, 'Ficciones', 'Jorge Luis Borges', 5);
INSERT INTO LIBROS (ID_LIBRO, TITULO, AUTOR, STOCK) VALUES (9, 'Azul', 'Rubén Darío', 8);
INSERT INTO LIBROS (ID_LIBRO, TITULO, AUTOR, STOCK) VALUES (10, 'Siddhartha', 'Hermann Hesse', 4);

-- 7.2 Insertar Usuarios (Lectorado de prueba)
INSERT INTO USUARIOS (ID_USUARIO, NOMBRE, CORREO) VALUES (101, 'Juan Perez', 'juan.perez@email.com');
INSERT INTO USUARIOS (ID_USUARIO, NOMBRE, CORREO) VALUES (102, 'Maria Lopez', 'm.lopez@email.com');
INSERT INTO USUARIOS (ID_USUARIO, NOMBRE, CORREO) VALUES (103, 'Carlos Ruiz', 'cruiz88@email.com');
INSERT INTO USUARIOS (ID_USUARIO, NOMBRE, CORREO) VALUES (104, 'Ana Gomez', 'anagomez@email.com');
INSERT INTO USUARIOS (ID_USUARIO, NOMBRE, CORREO) VALUES (105, 'Luis Diaz', 'ldiaz_bib@email.com');

-- 7.3 Registrar algunos préstamos iniciales (Para que la Vista tenga datos)
-- Nota: Se activara automáticamente el Trigger de reducción de Stock
INSERT INTO PRESTAMOS (ID_PRESTAMO, ID_LIBRO, ID_USUARIO, FECHA) VALUES (1, 1, 101, SYSDATE-5);
INSERT INTO PRESTAMOS (ID_PRESTAMO, ID_LIBRO, ID_USUARIO, FECHA) VALUES (2, 2, 102, SYSDATE-3);
INSERT INTO PRESTAMOS (ID_PRESTAMO, ID_LIBRO, ID_USUARIO, FECHA) VALUES (3, 6, 105, SYSDATE-1);

COMMIT;

-- Permisos para que el Bibliotecario vea la Vista y sus tablas origen
GRANT SELECT ON LIBROS TO BIBLIOTECARIO_PRACTICO;
GRANT SELECT ON USUARIOS TO BIBLIOTECARIO_PRACTICO;
GRANT SELECT ON PRESTAMOS TO BIBLIOTECARIO_PRACTICO;
GRANT SELECT ON VISTA_RESUMEN_PRESTAMOS TO BIBLIOTECARIO_PRACTICO;

COMMIT;


--------------------------------------------------------
-- 8. CIERRE Y VERIFICACIÓN DE CAJA NEGRA
--------------------------------------------------------
-- Prueba automática de la auditoría (Caja Negra)
INSERT INTO LIBROS (ID_LIBRO, TITULO, AUTOR, STOCK) 
VALUES (99, 'Base de Datos Pro', 'Admin Bib', 1);

DELETE FROM LIBROS WHERE ID_LIBRO = 99;

COMMIT;

PROMPT >>> SCRIPT EJECUTADO EXITOSAMENTE. SISTEMA DE BIBLIOTECA LISTO.